ddconfig:
    double_z: false
    z_channels: 16
    resolution: 32
    in_channels: 16
    out_ch: 16
    ch: 64
    ch_mult: [1, 2, 2]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    attn_type: "none"
embedconfig:
    n_embed: 1024
    embed_dim: 16
lossconfig:
    target: "src.models.modules.losses.SimpleVQVAELoss"