ddconfig:
    double_z: false
    z_channels: 8
    resolution: 32
    in_channels: 16
    out_ch: 16
    ch: 64
    ch_mult: [1, 2, 2]
    num_res_blocks: 2
    attn_resolutions: [16]
    dropout: 0.0
    attn_type: "vanilla"
    n_embed: 1024
    embed_dim: 64 # flattened dimension of the discrete indices
    remap: null
    sane_index_shape: true
lossconfig:
    target: "src.models.modules.losses.VQLPIPSWithDiscriminator"
    params:
        disc_start: 20000
        rec_img_weight: 1.0
        rec_lat_weight: 1.0
        perceptual_weight: 1.0
        codebook_weight: 0.25
        disc_weight: 0.5
        disc_num_layers: 3
        disc_in_channels: 3
        use_actnorm: false
        disc_loss: "hinge_r1"
        pixel_loss: "l1"
        n_embed: 1024
learning_rate: 1.0e-4