ddconfig:
    input_dim: 16384
    latent_dim: 512
lossconfig:
    target: "src.models.modules.losses.AutoencoderLPIPSWithDiscriminator"
    params:
        disc_start: 200
        rec_img_weight: 1.0
        rec_lat_weight: 1.0
        perceptual_weight: 1.0
        disc_weight: 0.5
        disc_num_layers: 3
        disc_in_channels: 3
        use_actnorm: false
        disc_loss: "hinge_r1"
        pixel_loss: "l1"
learning_rate: 1.0e-4