ddconfig:
    double_z: true
    z_channels: 32
    resolution: 32
    in_channels: 16
    out_ch: 16
    ch: 16
    ch_mult: [1, 2]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    attn_type: "none"
    embed_dim: 8192
lossconfig:
    target: "src.models.modules.losses.LPIPSWithDiscriminator"
    params:
        disc_start: 20000
        logvar_init: 0.0
        rec_img_weight: 1.0
        rec_lat_weight: 1.0
        perceptual_weight: 1.0
        kl_weight: 0.000001
        disc_weight: 0.5
        disc_num_layers: 3
        disc_in_channels: 3
        use_actnorm: false
        disc_loss: "hinge_r1"
learning_rate: 4.5e-6