ddconfig:
    double_z: false
    z_channels: 8
    resolution: 32
    in_channels: 16
    out_ch: 16
    ch: 64
    ch_mult: [1, 2, 2]
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
    attn_type: "vanilla"
    embed_dim: 512
lossconfig:
    target: "src.models.modules.losses.SimpleAutoencoderLoss"
learning_rate: 4.5e-6